apiVersion: v1
kind: Namespace
metadata:
  name: echo-backend
  labels:
    name: echo-backend
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-monitoring
  labels:
    name: echo-monitoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-infrastructure
  labels:
    name: echo-infrastructure
    environment: production
